from collections.abc import Iterator
from enum import Enum

class Bound(Enum):
    CLOSED = True
    OPEN = False


CLOSED: Bound
OPEN: Bound


class Interval[T]:
    def __init__(self, *intervals: Interval[T]) -> None: ...
    def __or__(self, other: Interval[T]) -> Interval[T]: ...
    def __and__(self, other: Interval[T]) -> Interval[T]: ...
    def __sub__(self, other: Interval[T]) -> Interval[T]: ...
    def __invert__(self) -> Interval[T]: ...
    def __contains__(self, item: T) -> bool: ...
    def __iter__(self) -> Iterator[Interval[T]]: ...
    @property
    def lower(self) -> T: ...
    @property
    def upper(self) -> T: ...
    @property
    def left(self) -> Bound: ...
    @property
    def right(self) -> Bound: ...
    @property
    def empty(self) -> bool: ...
    @property
    def atomic(self) -> bool: ...
    def replace(
        self,
        left: Bound | None = None,
        lower: T | None = None,
        upper: T | None = None,
        right: Bound | None = None,
        *, ignore_inf: bool = True
    ) -> Interval[T]: ...


def open[T](lower: T, upper: T) -> Interval[T]: ...
def closed[T](lower: T, upper: T) -> Interval[T]: ...
def openclosed[T](lower: T, upper: T) -> Interval[T]: ...
def closedopen[T](lower: T, upper: T) -> Interval[T]: ...
def singleton[T](value: T) -> Interval[T]: ...
def empty[T]() -> Interval[T]: ...
